image: "python:3.9"

before_script:
  - python --version
  - pip install pipenv
  - pipenv install --ignore-pipfile

stages:
  - Static Analysis

flake8:
  stage: Static Analysis
  script:
    - pipenv run flake8 --max-line-length=120 sample/*.py
